---
title: "Figure 3"
author: "Can Ulutekin"
date: "2023-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Cleanup

```{r}
rm(list = ls())
```

### Packages

```{r}
library(tidyverse)
library(openxlsx)
library(ggpubr)
```

### Load Data

```{r, warning=FALSE}
setwd("../../paper_data/validation_cohort/")
data <- readRDS("data_val_cyto.rds")
md <- read.xlsx("metadata.xlsx")

data_md <- data %>%
  dplyr::left_join(md, by = "patient_timepoint")

all_markers <- colnames(data)[3:38]
```

### Figure 3.A

```{r, warning=FALSE}
data_violin <- data_md %>%
  dplyr::filter(generic_diagnosis == "MS") %>%
  dplyr::filter(main_clusters == "CD4") %>%
  dplyr::group_by(patient_timepoint) %>%
  dplyr::add_tally(name = "CD4_count") %>%
  dplyr::ungroup() %>%
  dplyr::group_by(patient_timepoint, sub_clusters) %>%
  dplyr::add_tally(name = "CD4sub_count") %>%
  dplyr::ungroup() %>%
  dplyr::select(patient_timepoint, sub_clusters, CD4sub_count, CD4_count) %>% # total_count
  dplyr::distinct() %>%
  dplyr::mutate(CD4_comp = 100 * CD4sub_count / CD4_count) %>%
  dplyr::left_join(md, by = "patient_timepoint") %>%
  dplyr::mutate(treated = if_else(treatment_cycle == 0,
                                  "Before", "After",
                                  NA_character_)) %>%
  dplyr::mutate(sub_clusters = factor(sub_clusters,
                                      levels = c("Central Memory",
                                                 "Effector Memory",
                                                 "Naive",
                                                 "Follicular",
                                                 "CD103+"))) %>%
  dplyr::mutate(treated = factor(treated, levels = c("Before", "After"))) %>%
  dplyr::arrange(sub_clusters, patient_id, treated) %>%
  dplyr::filter(sub_clusters == "Follicular")

fig3.A <- ggplot(data_violin, aes(x = treated, y = CD4_comp, fill = treated)) +
  # stat_compare_means(comparisons = list(c("Before", "After")), paired = T) +
  geom_violin(scale ="area", alpha = 1, draw_quantiles = .5) +
  geom_point(size = 0.5) +
  geom_line(aes(group = patient_id), colour="black", linetype="11") +
  facet_wrap(~sub_clusters, scales = "free", nrow = 1) +
  scale_fill_manual(values = c("#abc3c9", "#e0dcd3")) +
  ylab("% of CD4+ T cells") +
  xlab("treatment") +
  theme_classic() +
  theme(legend.position = "none",
        strip.text.x = element_text(size = 7))

fig3.A

setwd("../figures")
pdf(file = "Figure_3A.pdf", width = 4, height = 5)
print(fig3.A)
invisible(dev.off())

rm(data_violin) # cleanup
```

### Figure 3.B

```{r, warning=FALSE}
data_violin <- data_md %>%
  dplyr::filter(generic_diagnosis == "MS") %>%
  dplyr::filter(main_clusters == "CD4") %>%
  dplyr::group_by(patient_timepoint, sub_clusters) %>%
  dplyr::summarise(across(.cols = all_of(all_markers), .fns = median)) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(md, by = "patient_timepoint") %>%
  dplyr::mutate(treated = if_else(treatment_cycle == 0,
                                  "Before", "After",
                                  NA_character_)) %>%
  dplyr::mutate(sub_clusters = factor(sub_clusters,
                                      levels = c("Central Memory",
                                                 "Effector Memory",
                                                 "Naive",
                                                 "Follicular",
                                                 "CD103+"))) %>%
  dplyr::mutate(treated = factor(treated, levels = c("Before", "After"))) %>%
  dplyr::filter(sub_clusters %in% c("Central Memory", "Effector Memory", "Follicular")) %>%
  dplyr::arrange(sub_clusters, patient_id, treated)

fig3.B <- ggplot(data_violin, aes(x = treated, y = CD27, fill = treated)) +
  # stat_compare_means(comparisons = list(c("Before", "After")), paired = T) +
  geom_violin(scale ="area", alpha = 1, draw_quantiles = .5) +
  geom_point(size = 0.5) +
  geom_line(aes(group = patient_id), colour="black", linetype="11") +
  facet_wrap(~sub_clusters, scales = "free", nrow = 1) +
  scale_fill_manual(values = c("#abc3c9", "#e0dcd3")) +
  ylab("median CD27 expression") +
  xlab("treatment") +
  theme_classic() +
  theme(legend.position = "none",
        strip.text.x = element_text(size = 7))

fig3.B

setwd("../figures")
pdf(file = "Figure_3B.pdf", width = 10, height = 5)
print(fig3.B)
invisible(dev.off())

rm(data_violin) # cleanup
```

### Figure 3.C

```{r, warning=FALSE}
data_violin <- data_md %>%
  dplyr::filter(generic_diagnosis == "MG") %>%
  dplyr::filter(main_clusters == "CD4") %>%
  dplyr::group_by(patient_timepoint) %>%
  dplyr::add_tally(name = "CD4_count") %>%
  dplyr::ungroup() %>%
  dplyr::group_by(patient_timepoint, sub_clusters) %>%
  dplyr::add_tally(name = "CD4sub_count") %>%
  dplyr::ungroup() %>%
  dplyr::select(patient_timepoint, sub_clusters, CD4sub_count, CD4_count) %>% # total_count
  dplyr::distinct() %>%
  dplyr::mutate(CD4_comp = 100 * CD4sub_count / CD4_count) %>%
  dplyr::left_join(md, by = "patient_timepoint") %>%
  dplyr::mutate(treated = if_else(treatment_cycle == 0,
                                  "Before", "After",
                                  NA_character_)) %>%
  dplyr::mutate(sub_clusters = factor(sub_clusters,
                                      levels = c("Central Memory",
                                                 "Effector Memory",
                                                 "Naive",
                                                 "Follicular",
                                                 "CD103+"))) %>%
  dplyr::mutate(treated = factor(treated, levels = c("Before", "After"))) %>%
  dplyr::arrange(sub_clusters, patient_id, treated) %>%
  dplyr::filter(sub_clusters == "Follicular")

fig3.C <- ggplot(data_violin, aes(x = treated, y = CD4_comp, fill = treated)) +
  # stat_compare_means(comparisons = list(c("Before", "After")), paired = T) +
  geom_violin(scale ="area", alpha = 1, draw_quantiles = .5) +
  geom_point(size = 0.5) +
  geom_line(aes(group = patient_id), colour="black", linetype="11") +
  facet_wrap(~sub_clusters, scales = "free", nrow = 1) +
  scale_fill_manual(values = c("#abc3c9", "#e0dcd3")) +
  ylab("% of CD4+ T cells") +
  xlab("treatment") +
  theme_classic() +
  theme(legend.position = "none",
        strip.text.x = element_text(size = 7))

fig3.C

setwd("../figures")
pdf(file = "Figure_3C.pdf", width = 4, height = 5)
print(fig3.C)
invisible(dev.off())

rm(data_violin) # cleanup
```

### Figure 3.D

```{r, warning=FALSE}
data_violin <- data_md %>%
  dplyr::filter(generic_diagnosis == "MG") %>%
  dplyr::filter(main_clusters == "CD4") %>%
  dplyr::group_by(patient_timepoint, sub_clusters) %>%
  dplyr::summarise(across(.cols = all_of(all_markers), .fns = median)) %>%
  dplyr::ungroup() %>%
  dplyr::left_join(md, by = "patient_timepoint") %>%
  dplyr::mutate(treated = if_else(treatment_cycle == 0,
                                  "Before", "After",
                                  NA_character_)) %>%
  dplyr::mutate(sub_clusters = factor(sub_clusters,
                                      levels = c("Central Memory",
                                                 "Effector Memory",
                                                 "Naive",
                                                 "Follicular",
                                                 "CD103+"))) %>%
  dplyr::mutate(treated = factor(treated, levels = c("Before", "After"))) %>%
  dplyr::filter(sub_clusters %in% c("Central Memory", "Effector Memory", "Follicular")) %>%
  dplyr::arrange(sub_clusters, patient_id, treated)

fig3.D <- ggplot(data_violin, aes(x = treated, y = CD27, fill = treated)) +
  # stat_compare_means(comparisons = list(c("Before", "After")), paired = T) +
  geom_violin(scale ="area", alpha = 1, draw_quantiles = .5) +
  geom_point(size = 0.5) +
  geom_line(aes(group = patient_id), colour="black", linetype="11") +
  facet_wrap(~sub_clusters, scales = "free", nrow = 1) +
  scale_fill_manual(values = c("#abc3c9", "#e0dcd3")) +
  ylab("median CD27 expression") +
  xlab("treatment") +
  theme_classic() +
  theme(legend.position = "none",
        strip.text.x = element_text(size = 7))

fig3.D

setwd("../figures")
pdf(file = "Figure_3D.pdf", width = 10, height = 5)
print(fig3.D)
invisible(dev.off())

rm(data_violin) # cleanup
```